CREATE TABLE USERS (
  ID INT(10) NOT NULL PRIMARY KEY,
  USERNAME VARCHAR(30) NOT NULL,
  PASSWORD VARCHAR(60) NOT NULL,
  ENABLED BOOLEAN NOT NULL
);

CREATE TABLE AUTHORITIES (
  USER_ID INT(10) NOT NULL,
  AUTHORITY VARCHAR(50) NOT NULL,
  CONSTRAINT FK_AUTHORITIES_USERS FOREIGN KEY(USER_ID) REFERENCES USERS(ID)
);

CREATE UNIQUE INDEX X_AUTH_USERNAME ON AUTHORITIES (USER_ID, AUTHORITY);


INSERT INTO USERS(ID, USERNAME, PASSWORD, ENABLED) VALUES (1, 'admin', 'admin', true);
INSERT INTO USERS(ID, USERNAME, PASSWORD, ENABLED) VALUES (2, 'alex', 'alex', true);

INSERT INTO AUTHORITIES (USER_ID, AUTHORITY) VALUE (1, 'ROLE_ADMIN');
INSERT INTO AUTHORITIES (USER_ID, AUTHORITY) VALUE (1, 'ROLE_USER');
INSERT INTO AUTHORITIES (USER_ID, AUTHORITY) VALUE (2, 'ROLE_USER');

